services:
  mysql:
    image: mysql:8.4
    container_name: cinemasso-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdcinemasso
    ports:
      - "3306:3306"
    volumes:
      - cinemasso_mysql:/var/lib/mysql
volumes:
  cinemasso_mysql:
